name: Audit HTML Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Setiap hari jam 10:00 WIB (03:00 UTC)

jobs:
  audit-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install requests

      - name: Jalankan Audit
        run: python audit/audit-html.py

      - name: Konfigurasi Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit dan Push Hasil Audit
        run: |
          git add audit/audit-log.txt
          git commit -m "🔍 Auto audit: update audit-log.txt"
          git push
        continue-on-error: true
